spring.application.name=rpg

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/control-rpg}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# URL do servidor do rival para as batalhas em rede
rival.url=http://localhost:8080/

server.port=${PORT:8080}
server.address=0.0.0.0


# spring.jpa.hibernate.ddl-auto:
# Faz com que o Hibernate crie ou atualize as tabelas no PostgreSQL automaticamente
# com base nas classes Kotlin, sem que precise digitar comandos CREATE TABLE manualmente db.

# spring.jpa.show-sql=true:
# Mostra no console da IDE os comandos SQL reais que o Spring esta executando.
